/-
Copyright (c) 2024-2025 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Katerina Hristova, Ilia Vlasov
-/

import Mathlib.Algebra.Polynomial.Basic
import Mathlib.Algebra.Polynomial.Bivariate
import Mathlib.Algebra.Polynomial.Eval.Irreducible
import Mathlib.FieldTheory.RatFunc.Basic
import Mathlib.FieldTheory.Separable
import Mathlib.RingTheory.Ideal.Maximal
import Mathlib.RingTheory.Ideal.Span
import Mathlib.RingTheory.Polynomial.Resultant.Basic

open scoped Polynomial

/-!
  # Preliminary Definitions and Theorems on polynomials and rings of rational functions.

  In this file, we state the needed definition and lemmas from general polynomial theory and
  commutative algebra needed to state and/or prove results on rational functions and bivariate
  polynomials.

  We divide the file into three sections : Univariate, containing results on univariate polynomials,
  Ideal, containing results relating rings and their ideals, and RatFunc, containing some
  preliminaries relating rational functions to polynomials.

  ## Main Definitions
  -- In Univariate, we define a discriminant of a polynomial and state lemmas relating discriminants
  to resultants and separability. -- In Ideal, we define principal ideals, and state the well-known
  result from commutative algebra that a principal ideal in a polynomial ring is maximal if and only
  if it is generated by an irreducible polynomial. -- In RatFunc, we define the needed algebra
  homomorphisms enabling us to lift univariate and bivariate polynomials to rational functions.

  TODO: if / when this file gets too large, we need to split it into smaller files (esp. since the
  definitions are distinct)
-/

open Polynomial
open Polynomial.Bivariate

namespace Univariate

section

/-- Discriminant of a univariate polynomial. -/
noncomputable def discriminant {F : Type} [Field F] [Inhabited F] (f : F[X]) : F :=
  1/f.leadingCoeff * Polynomial.resultant f (Polynomial.derivative f)

/-- The resultant of a polynomial is divisible by its leading coefficient. -/
lemma resultant_is_divisible_by_leadingCoeff {F : Type} [CommRing F] [Inhabited F] (f : F[X])
  : ∃ r',
    Polynomial.resultant f (Polynomial.derivative f) = f.leadingCoeff * r'
    := by sorry

/-- A polynomial is separable if and only if its discriminant is non-zero. -/
lemma separable_iff_discr_eq_zero {F : Type} [Field F] [Inhabited F] (f : F[X]) :
  f.Separable ↔ discriminant f ≠ 0 := by sorry

end
end Univariate

namespace Ideal
section

/-- A principal ideal is an ideal generated by a single element. -/
def principalIdeal {F : Type} [Semiring F] (f : F) : Ideal F := Ideal.span {f}

end
end Ideal

namespace ToRatFunc
noncomputable section

/-- The algebra map embedding the univariate polynomial ring into its ring of rational functions. -/
def univPolyHom {F : Type} [CommRing F] [IsDomain F] : F[X] →+* RatFunc F :=
  algebraMap (F[X]) (RatFunc F)


/-- The algebra map embedding the bivariate polynomial ring into its ring of rational functions. -/
def bivPolyHom {F : Type} [CommRing F] [IsDomain F] :
  Polynomial (F[X]) →+* Polynomial (RatFunc F) := Polynomial.mapRingHom (univPolyHom)

end
end ToRatFunc

def principalIdeal {R : Type*} [Semiring R] (r : R) : Ideal R :=
  Ideal.span ({r} : Set R)

theorem irreducible_of_principalIdeal_isMaximal {F : Type*} [Field F] (f : F[X])
    (hmax : (principalIdeal f).IsMaximal) : Irreducible f := by
  classical
  -- Step 1: show `f ≠ 0` using that `F[X]` is not a field
  have hnebot : (principalIdeal f : Ideal F[X]) ≠ ⊥ :=
    Ring.ne_bot_of_isMaximal_of_not_isField hmax (Ideal.polynomial_not_isField (R := F))
  have hf0 : f ≠ 0 := by
    intro hf
    apply hnebot
    simp [principalIdeal, hf]
  -- Step 2: maximal ideals are prime
  have hprimeI : (principalIdeal f : Ideal F[X]).IsPrime := hmax.isPrime
  -- Step 3: a prime principal ideal gives a prime element
  have hprimeSpan : (Ideal.span ({f} : Set F[X])).IsPrime := by
    simpa [principalIdeal] using hprimeI
  have hprimeElem : Prime f := (Ideal.span_singleton_prime (p := f) hf0).1 hprimeSpan
  -- Step 4: prime implies irreducible
  exact hprimeElem.irreducible

theorem principalIdeal_isMaximal_of_irreducible {F : Type*} [Field F] (f : F[X])
    (hf : Irreducible f) : (principalIdeal f).IsMaximal := by
  classical
  letI : Fact (Irreducible f) := ⟨hf⟩
  simpa [principalIdeal] using
    (by infer_instance : (Ideal.span ({f} : Set F[X])).IsMaximal)

theorem principal_is_maximal_iff_irred {F : Type*} [Field F] (f : F[X]) :
    (principalIdeal f).IsMaximal ↔ Irreducible f := by
  constructor
  · intro hmax
    exact irreducible_of_principalIdeal_isMaximal f hmax
  · intro hirr
    exact principalIdeal_isMaximal_of_irreducible f hirr
